@startuml diagrama-configuracao
skinparam classAttributeIconSize 0
skinparam classFontStyle Bold
title Domínio: configuracao\n(Padrão: Singleton)

class ConfiguracaoRestaurante {
  - {static} instancia : ConfiguracaoRestaurante
  - nomeRestaurante : String
  - endereco : String
  - horario : String
  - taxaEntrega : double
  --
  - ConfiguracaoRestaurante()
  + {static} getInstance() : ConfiguracaoRestaurante
  + getNomeRestaurante() : String
  + setNomeRestaurante(n : String)
  + getEndereco() : String
  + getHorario() : String
  + getTaxaEntrega() : double
}

note right of ConfiguracaoRestaurante
  <b>Singleton</b>
  Instância única das
  configurações do restaurante
end note
@enduml
